name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Installing Deps & Building
        run: pnpm install
      - name: Testing & Coverage
        run: pnpm test
      - name: Uploading Coverage Report
        uses: codecov/codecov-action@v2
        with:
          flags: core
          directory: packages/core
        uses: codecov/codecov-action@v2
        with:
          flags: shared
          directory: packages/shared
